# Generated by Django 4.0.1 on 2022-01-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('direccion', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
